### ISSUE TITLE
Notification "Retrying" without a known reason

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#145]
While navigating with Alt-Up and Alt-Down through the Bible text in the visual verse editor, the notification "Retrying" pops up very often. Yet, there is no known reason for doing so. Normally the popup comes up when it fails to save changed text. But in this case, no text was saved. It may be necessary to navigate quickly for this behaviour to come up.

**Comment by alerque** [comment]
This bug appears to be a logic flaw. I have no idea why [L201 or editone/index.js](https://github.com/teusbenschop/bibledit/blob/master/lib/editone/index.js#L201) has this notification at all but you added it in 2b00d720. The only reason you never noticed it before is because there was a bogus variable name being passed in. When I fixed the variable name (55c5bf1) the message started getting passed to the notify function instead of raising a syntax error.

**Comment by teusbenschop** [comment]
The reason for this notification is to indicate a Bible text save failure. The cause of the failure may be manifold, like a bad internet connection, or saving non-UTF-8 text, or saving too many changes in one go. There's other reasons also causing such popup notifications.
