### ISSUE TITLE
Standard Hebrew resources hard to read

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#157]
The standard Hebrew resources Hebrew (Open Scriptures) and Hebrew (University of Amsterdam) used to have word spaced naturally such that they could easily be read.
But now some words are not separated at all, making them hard to read.
And the lines are now separated such that the vowel markers and punctuation of two lines mix together, making it impossible to read, which can lead to translation errors.
![screen shot 2016-04-22 at 12 50 07](https://cloud.githubusercontent.com/assets/1310167/14739581/c8e8b58e-0888-11e6-9249-6079947af1e4.png)

**Comment by teusbenschop** [comment]
It used to leave most line and word spacing to the browser which always led to naturally well looking spacing. But the new CSS seems to override this.

**Comment by alerque** [comment]
I didn't do anything to work spacing, and line spacing was set as a factor of the text height which should work for nearly any language content. I'm not sure what's up with this, but I'll  have a look. I definitely see the problem.

**Comment by teusbenschop** [comment]
Perhaps it helps to not set the line spacing, so the browser takes the special properties of Hebrew characters in account...

**Comment by alerque** [comment]
This is not actually a function of the line height setting at all. Even though I made a mistake there, the real problem here has to do with the fact those resources are diced up into tabels and not using normal word or line spacing mechanisms.

**Comment by teusbenschop** [comment]
I'll have to look into this one deeper, but as a reminder for myself, here's something that I could use: https://css-tricks.com/almanac/properties/a/all/
It would reset inherited values for class "hebrew".

**Comment by alerque** [comment]
That's a cool trick but probably not a good idea here. For starters it has browser support issues, notable none for Safari or Android. Even if it did work, it would kind of screw up inheritance for properties we _do_ want to keep cohesive across the app. If that rule would really fix something we're probably doing it wrong higher up and since we control the top of the cascade we're in a position to fix it at the root instead of downstream.

I'm working on interlinear tables but having computer trouble and landline internet in my city is on the fritz today.
