### ISSUE TITLE
Build the Windows port outside of the source tree

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#171]
Building the Windows port currently leads to duplicate code in the source tree. This is because the build is done in the Windows source tree itself. If the Windows port could be built outside of the source tree, that would help in that it no longer duplicates code.

**Comment by alerque** [comment]
If possible please don't do big bulk file moves (as happened yesterday to the Linux port) in the near future. I'm rewriting the paths automatically for the repo migration and every big change like that is something I have to add an exception case to work around.

**Comment by teusbenschop** [comment]
OK, thanks for the info, I am writing a note here for myself to not do the bulk file moves for the Windows port (and others if any are left) till after you have completed the repository migration.

**Comment by teusbenschop** [comment]
To avoid the bulk file moves, and at the same time work on an automatic builder, what I can do is to leave the Windows-related files, that becomes superfluous after building in a temporal location, in place for the time being, and then once the repository has split up, to only then to the bulk file moves.

**Comment by alerque** [comment]
I'm a little confused by that description. What files exactly are we talking about here? Can you give me an example of a file and where you see it moving from/to?

**Comment by teusbenschop** [comment]
I was unclear in using the word "move", because there will be no moving of files. What happens is that the files in windows/webroot (https://github.com/teusbenschop/bibledit/tree/master/windows/webroot) are all duplicates of the core library. These duplicates are now checked into the git repository. When building outside the source tree, then all files in windows/webroot are superfluous. They can then be removed from the git repository. And removing so many files in bulk, once off, is what I meant. So, leaving those files in their places for the time being, that avoids large changes to the repository. Those large changes in the repository would probably give you more work - and that's the last thing I would want to do!

**Comment by alerque** [comment]
Ha got it. So this removal _already is_ a part of the migration process. All the duplicated stuff is getting removed and each platform is being stripped down to just the components that are part of _that_ platform. The stuff that was previously in "lib" (or various copies of that content in platform specific folders) is called "bibledit-core" and is a sub-module inside each platform repo. Getting all the paths wired up again so that things build is a large part of what's holding up the migration.

So yes, having a lot of paths change right now is not a good idea unless we coordinate on what changes I've patched already. Otherwise I'm destined for the infernos of merge conflict purgatory!

**Comment by teusbenschop** [comment]
Ah, the removal is already part of the migration path! No need for me to worry about those files then.

Wishing you well with it, and I am looking forward to how the new repo layout will look and feel!
