### ISSUE TITLE
Staten Bible Resource lacks italics and bold

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#176]
The original text of the Staten Bible Resource has italics, but after fetching it and filtering it, and displaying it within Bibledit, the italics are no longer there. The same applies to the words in bold.

**Comment by alerque** [comment]
Is this a function of the filtering removing the markup or the stylesheet not having a rule?

**Comment by teusbenschop** [comment]
It's the C++ filter that incorrectly removes the markup, and I'm going to fix it speedily because it itches our team :)

**Comment by teusbenschop** [comment]
It appears to be that the 
`
<i>
` 
tag (http://www.w3schools.com/tags/tag_i.asp) does not get rendered, I'm going to look into which rule to add.

**Comment by teusbenschop** [comment]
The i tag is in the CSS resets in the default stylesheet.css. Is there a reason for it being there, or can the i tag be removed from the resets?

**Comment by alerque** [comment]
The resets should stay because—especially in the context of mixed content being used for less than semantic purposes—we don't want to rely on the default browser's style sheet. That being said adding styling for `<i>` and `<em>` as `font-style: italic` and `<b>` and `<strong>` as `font-weight: bold` is fine. It should just be done after the resets, maybe about where the paragraph stuff gets set.

If you have the choice, use the semantic emphasis/strong versions of the tag instead of the inline style italic/bold versions. Not a big deal if you have somebody else's source, but better to use the right tags ourselves.

**Comment by teusbenschop** [comment]
Yes, better to be correct ourselves - perhaps there could be some old html 4 markup but I am not aware of it off the top of my head.
Perhaps the import filter for the Staten Bible should translate the "i" and "b" styles, but I am not a perfectionist enough to be spending time on it right now, perhaps later... :)

**Comment by alerque** [comment]
If we start transforming markup rather than just filtering it, there are a _lot_ of things we could fix. It might be worth doing sometime, but only if it was done wholeheartedly. <i>→<em> by itself isn't worth troubling about right now, our time would be more valued spent on other problems.

**Comment by teusbenschop** [comment]
I agree, we've more important issues to focus on right now :)

As for https://github.com/teusbenschop/bibledit/pull/180/commits/7fee1fd4afdeed9b617fc0323c6ca8aecabed901, it's very weird, I have merged it, but can't find it now in https://github.com/teusbenschop/bibledit/blob/master/lib/css/stylesheet.css

**Comment by alerque** [comment]
You appear to have force-pushed to the master branch after merging the PR and before pulling the changes into your client. I would make sure the `--force` switch is turned off by default in your git client because that can be nasty if not used knowing the side effects.

At this point I would just cherry pick the commit back in. Add me as a remote if you haven't already and cherry pick the commit:

```
git remote add alerque https://github.com/alerque/bibledit.git
git fetch --all
git cherry-pick 7fee1fd
```

**Comment by teusbenschop** [comment]
The commit is now back in, thanks.

But what is weird is that Github's own Mac client is force-pushing things.

![screen shot 2016-05-12 at 17 39 20](https://cloud.githubusercontent.com/assets/1310167/15220675/9a2621a6-1868-11e6-8a2a-e63a6c1a33eb.png)

I just press the "Sync" button at the top-right of the screen, and it always works fine after applying pull requests from you. I've made no changes to the settings in GitHub Client.

This is the .git/config file:

``` [core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
[remote "origin"]
    fetch = +refs/heads/*:refs/remotes/origin/*
    url = https://github.com/teusbenschop/bibledit.git
[branch "master"]
    remote = origin
    merge = refs/heads/master
[branch "revert-99-layout-border-boxes"]
    remote = origin
    merge = refs/heads/revert-99-layout-border-boxes
[branch "teus"]
    remote = origin
    merge = refs/heads/teus
[remote "alerque"]
    url = https://github.com/alerque/bibledit.git
    fetch = +refs/heads/*:refs/remotes/alerque/*
```
