### ISSUE TITLE
cannot scroll through resources in resource organizer

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#187]
On touch enabled devices, when there's a large amount of resources in the resource organizer, one cannot scroll through them with the finger, because doing so just moves a resources to another location, rather than scrolling through the page.

**Comment by alerque** [comment]
If all the items on the page have drag handlers it's going to be tricky to scroll. Two paradigms to work around this are to
- keep some margin and other UI elements around on the page that are big enough to hit
- use a drag handle on one small part of the item rather than making the whole item a target

I'm inclined to think the latter is a better approach here because it isn't obvious that the items _can_ be dragged until you try, while a drag handle is becoming a fairly recognizable UI element, esp. on mobile.

Thoughts?

**Comment by teusbenschop** [comment]
Yes, I agree with you that adding a visible drag handle on a small part of the item is a good approach to solving this.

**Comment by teusbenschop** [comment]
This is a duplicate from https://github.com/teusbenschop/bibledit/issues/115 so I am closing the other issue.

**Comment by teusbenschop** [comment]
There's a helpful link about drag and drop on touch devices:
http://ux.stackexchange.com/questions/24321/drag-n-drop-on-touch-devices
So I thought that there's no reason to be different from what's usually being done on touch devices, and therefore that there should be another way to reorder the items in the list.
