### ISSUE TITLE
Look into Quick Bible app

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#229]
Whether exporting to a format Quick Bible can read requires something or whether this already works.

**Comment by kingjimmy** [comment]
i'm trying to see that again. for some reason the initial look into this seemed confusing /ie no mention of stnd bible codes (usfm) etc to convert to the.yet format needed to then use java to compile to the.yes format for quick bible use --i wonder it one of the html formats have the needed codes (??)

**Comment by kingjimmy** [comment]
oh, i remember yuku mentioned to "fork" him on git-hub.. --i will attamprt that...

**Comment by teusbenschop** [comment]
Some links:

http://www.bibleforandroid.com/developer

https://github.com/yukukuku/androidbible

**Comment by kingjimmy** [comment]
great looking at the example .yet file --that i opnend w notepad ++  the format seems v. similar to the VPL --from the Hailoa export --only there are @@ i think for "indents" --or else it says "tabs" in the instructions...

would be interesting to know if the Haiola can be "told" to use tab instead of the 1:1  and 1:2 format it uses then the file could "run" i would thinkafter only compiling that with the Java JAR command to go from .yet to .yes

if that works - i would think those "indents" (4 appearance of paragraph i guess --could be put in with search /replace --unless there's a better way --i know on the 1rst v. of Tongan Bible we used the "pilcrows" so that would be a snap to S and R for that --for whole Bible ,, boom!  anyway will see i guess!! :-)
