### ISSUE TITLE
C/C++ zip library

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#324]
To use a C or C++ ZIP library, rather than using the shell for that. This enables clients to zip and unzip stuff. Example: https://nih.at/libzip/index.html

**Comment by teusbenschop** [comment]
The combination of libzip-1.1.3 and zlib-1.2.8 would do. But the more important issue is this: Where's the functional requirement for having zip and unzip on clients? I cannot now find feature requests for this.

**Comment by alerque** [comment]
If we ever did have a need to package and send large amounts of data or mixed data types back an forth  between client and server, zip isn't the format we'd want to use anyway. There are much more standard ones in this space. Since we control both the client and server it would make even more sense to use the best available algorithm and put [zstd](https://github.com/facebook/zstd) on both sides of the line.

Only if we're parsing user supplied data or having to bundle things up to give to a user for consumption outside of BE would zip be something to consider implementing.

**Comment by teusbenschop** [comment]
It's good to keep this in mind if ever a case for this arises.
