### ISSUE TITLE
html list items no longer show their bullets or numerals

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#328]
For a while now, html list items no longer show their bullets or numerals. This needs a fix in the stylesheet.css. Likely the resets for the lists items should not reset the bullets or numerals.

**Comment by alerque** [comment]
This is a standard reset item and I left it in on behalf of the menus and other UI elements using more structural markup. It needs overriding for the sections of markup that specifically need presentational markup. I think I fixed it in the documentation and settings pages (from memory) but we should probably identify a common ancestor or DOM class that we can apply this to.

**Comment by teusbenschop** [comment]
Due to these resets in the stylesheet.css, there's is no visible difference between ol and ul, and I think this is not correct, else why have those two types of lists. I feel that it would be more correct to not reset the list items in html. That honours their properties as ordered or unordered lists, as intended by the W3C Working Group, see https://www.w3.org/TR/html-markup/ul.html for example, and https://www.w3.org/TR/html-markup/ol.html.

**Comment by alerque** [comment]
Wait is the issue that ol and ul aren't differentiated or that they don't have list styling at all? The styling reset is because browser defaults differ pretty radically in this department and its very difficult to style menus if you don't reset everything and start from scratch.

It now sounds like all we're missing is `ol { list-style-type: decimal; }` applied to the content area where lists are actually going to be lists and not menus or something else.

**Comment by teusbenschop** [comment]
The ol and the ul are not differentiated, and also they don't have a list styling at all.

My preference would be to give the default styling to ol and ul to make them appear as either ordered or unordered lists. Probably the proper thing to do is that the menus are coded differently so they don't generate ol and ul anymore, but something else.
