### ISSUE TITLE
Too-long URIs in notes pane

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#361]
Recently I've had a couple users with intermittent trouble reaching the notes pane in their workspaces. They get a message like this

> # Submitted URI too large!
> 
> The length of the requested URL exceeds the capacity limit for this server. The request cannot be processed. 

![selection_257](https://cloud.githubusercontent.com/assets/173595/19267005/fafc59d2-8fb4-11e6-96f7-7d7b8f0ea51d.png)

This is obviously from the proxy server I have sitting in front of Bibledit and something that may not manifest itself so easily when working with a direct connection. I'm also not sure of the exact conditions when this happens because It isn't consistent, but at the very least it sometimes happens on the notes list view. Leaving it open in one window while navigating to passages in another can eventually trigger this.

Obviously I could raise the URI length limit on the proxy, but I suspect the default is already quite as hight as it ought ever to be. Instead I suspect BE is either allowing things to build up by repeatedly appending parameters or else it's trying to pass data that should be moving through POST requests via GET parameters. The underlying issue should probably be addressed rather than expecting special configuration out of a proxy server.

**Comment by teusbenschop** [comment]
This is going to be looking for a needle in a haystack! It would help a tremendous lot if there were error logs on the proxy server that might give an indication of what causes the submitted URI to be too large.

**Comment by teusbenschop** [comment]
I now remember that I've had the very odd case of a very long URL somewhere in the consultation notes, and am trying to remember very hard what caused it. It was rare, very rare. 

Trying to remember what happened, it could well be the server being upgraded, and displaying the setup screen where to enter admin data, and that the server is being accessed while doing notes, so there could be build up of the URL.

Test case would be to work on notes on a cloud instance, then cause it to upgrade while working. But I may be wrong about this, because the instances were very rare.

**Comment by alerque** [comment]
Unfortunately I wasn't watching at the times this was reported and didn't have logging that would be useful. I'll keep an eye on it and follow up when I have more useful info.

**Comment by teusbenschop** [comment]
Has there been any more information on this one?

**Comment by alerque** [comment]
It's going to  be a couple weeks before we get a team together and do another stint. I'll try to test for this when it gets some use.

**Comment by teusbenschop** [comment]
That would help, thanks!
