### ISSUE TITLE
Ignore allowed punctuation marks when running checks 

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#392]
I just had a look at how the *Checks* tool was doing for our translation entry and it is flooded with useless entries to the point where the useful bits are hard to spot. I could go through them one at a time and add exceptions, but  that would break the actual functionality if the verse were to change for some reason (we're in the very rough draft stage so that's possible).

The most obvious thing I can see to fix is that the `Checks_Verses::missingPunctuationAtEnd()` and `Checks_Sentences::paragraphs()` functions need to take into account punctuation that is allowed "anywhere". I first thought the fact that my USFM has typographic quote marks (`“`, `”`, `‘`, `’`, etc.) was throwing it off, but I entered those into the allowed punctuation marks and I am still seeing paragraphs that begin or verses that end with these marks throwing errors about not being capitalized or punctuated. Basically the allowed punctuation characters should be stripped from the string before running these checks.

**Comment by teusbenschop** [comment]
I had a look at `Checks_Sentences::paragraphs` whether it could filter out the allowed punctuation, and it appears that it already did that, but in `Checks_Sentences::check`, which runs before. The code in that method was optimized just now but basically doing the same thing, that is, remove the allowed punctuation from the input stream.

Method `Checks_Verses::missingPunctuationAtEnd()` has been updated to strip the allowed punctuation away from the text stream to be checked.

So that means that everything should be okay now, in theory at least.

If it is not yet working as expected, it would help to receive samples of text and punctuation settings that cause undesired output. These could be used for unit tests and then for fixing the routines.
