### ISSUE TITLE
New files for catholic versification

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#401]
Hi,
I discovered that the Catholic 1 into the versification propositions,
was completely false. For this reason, I took as model the Catholic 2
from Sword. And I correct the xml file from bibledit-gtk. I made a new
versication for bibledit web Catholic2.txt.
I send you every thing, that you can add it to the software.
I made still correction into the po of bibledit-gtk, I send it again.
And I added new strings for the deuterocanonicals books into the
language_french_tob.xml. I don't know what means the "tob", if you
think it's better to do a new file do as you want.

Best regards, Br Cyrille

Three files attached, compressed.

[Archive.zip](https://github.com/bibledit/bibledit/files/614355/Archive.zip)

**Comment by LAfricain** [comment]
One new versification (Catholic1, as the Catholic on Sword, that means Esther with 10 chapters) and other files with new corrections.
Just a problem (?) with the the language_french_tob.xml, the 1 and 2 Maccabees  display to french (bibledit-gtk) only if you add two "white" categories like that at the end of the file:
`</book>`
`<english></english>`
`<localization></localization>`
`<abbreviation></abbreviation>`
`<book>`
`<english></english>`
`<localization></localization>`
`<abbreviation></abbreviation>`
`</book>`
Otherwise it display in English
[Archive.zip](https://github.com/bibledit/bibledit/files/644474/Archive.zip)
