### ISSUE TITLE
Tag git commits with user that generated the changes

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#92]
It's nice that Bibledit keeps it's backend in Git but hides most of the complexity of this from the user. However it's also destroying some of the meta data that _should_ exist even if most people may not use it. I'm quite accustomed to managing both code and data in Git and have a lot of tools at my disposal. Unfortunately the data being generated is not easy to manipulate.

Right off the bat the biggest item I've run into is keeping track of users. I have multiple typists filling in copy from hand written sheets. They seem to be able to edit in different chapters, then switch and check each-other's work. Sadly this is not leaving a trail that can be followed in git because the commits are all tagged with the generic user of the Cloud instance.

I propose that (optionally?) all git commits should be tagged with the name and and email of the logged in user. This would allow other tools to audit the history, generate stats on progress per user, highlight who is making what typos, etc.

**Comment by teusbenschop** [comment]
There used to be a "History" tool in Bibledit itself that would track the changes made per user. It was removed after some time.
Currently there are the change notifications in Bibledit, and they track the changes per user, but are volatile in the sense that any change notifications older than a month will be automatically removed.
When a translations manager reviews the change notifications regularly, it becomes clear who is making what typos, it becomes clear who is making what progress, who makes a lot of changes, who is slow. I think all of the information you mention is now available from within Bibledit (apart from that this information is not stored permanently.).
I do favour the idea of gaining insight in the production workflow of the various translators.

**Comment by teusbenschop** [comment]
Apart from tagging a commit with the username and email, would it not be more natural to set the author of the commit to the username and email? If it were possible to do this:

```
git commit --author="Name <email>" -m "whatever"
```

... then it would look as if each user made his/her commit in person.
I assume that existing tools to sort out data per user would then automatically work as expected.
I am going to start on this path and expect it to go well.

**Comment by alerque** [comment]
Yes. I actually tried to do this on my own and for some reason ran into situations where it would refuse to  commit at all—with no error. I'm not sure if this was a function of my test environment being broken or if I was coding something wrong, but here is the patch as of the last place I left it:

``` cpp
From 9c75513953781cb128ff6ecb78b3031241e5ee52 Mon Sep 17 00:00:00 2001
From: Caleb Maclennan <caleb@alerque.com>
Date: Mon, 21 Mar 2016 15:52:34 +0200
Subject: [PATCH] Record current user in git commits

Signed-off-by: Caleb Maclennan <caleb@alerque.com>
---
 lib/filter/git.cpp | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/lib/filter/git.cpp b/lib/filter/git.cpp
index 54052fb..56d13ae 100644
--- a/lib/filter/git.cpp
+++ b/lib/filter/git.cpp
@@ -32,6 +32,7 @@
 #endif
 #include <bible/logic.h>
 #include <locale/translate.h>
+#include <webserver/request.h>


 // This function returns the directory of the git repository belonging to $object.
@@ -629,8 +630,12 @@ bool filter_git_commit (string repository, string user, string email, string mes
 // It is needed because so far the libgit2 calls, in the parallel function, do not yet do the same as the shell call.
 bool filter_git_commit (string repository, string message, vector <string> & messages)
 {
+  Webserver_Request * request;
+  string username = request->session_logic()->currentUser ();
+  string email = request->database_users()->getUserToEmail (username);
+  string author = username + " <" + email + ">";
   string out, err;
-  int result = filter_shell_run (repository, "git", {"commit", "-a", "-m", message}, &out, &err);
+  int result = filter_shell_run (repository, "git", {"commit", "-a", "-m", message, "--author", author}, &out, &err);
   out = filter_string_trim (out);
   err = filter_string_trim (err);
   messages = filter_string_explode (out, '\n');
-- 
2.8.0
```

**Comment by teusbenschop** [comment]
OK, thank you for the patch and the warning: I'll look into this behaviour thoroughly to be sure that it really does commit.

**Comment by teusbenschop** [comment]
I think what happens is that 

```
request->session_logic()->currentUser ();
```

always returns an empty username.
This is because Bibledit runs this routine of sending and receiving to/from git as a scheduled task, and there's no user set for a scheduled task.

**Comment by alerque** [comment]
Also a question that came up while coding is where to get the name field from. In my attempt to deal with it I just used the username, but the username isn't necessarily the fullname. In my case all my users have unix style usernames that are the lower case versions of their first names with an optional last initial if they need disambiguating. However I would like the git commits to use everybody's full name. That means the user table actually needs another field, or there needs to be some administrator controlled mechanism to map Bibledit users to git identities.

**Comment by teusbenschop** [comment]
Currently Bibledit does allow to use full names for logging in, so it looks like the functionality is already there. There's no concept of 'username' and 'full name' in Bibledit as in some operating systems. When commit in git, after implementing this, it will just use whatever username was picked for a user's account.

**Comment by teusbenschop** [comment]
This one is now ready for prime time.... :) I am going to test it in our translation team.

**Comment by alerque** [comment]
I'm looking forward to updating my production instance!

**Comment by teusbenschop** [comment]
When different users work on the same chapter, there's a special mechanism to keep all commits per user per chapter together. So "system" commits can be found in rare cases in order to achieve that goal. If user A changes a word, and user B changes that same word also, then the first commit will show the changes of user A. The second commit prepares for the commit for user B: This second commit is the system commit, that reverts the text to reflect the text as it was before user B changed that same word. Then the third commit clearly and cleanly shows the change that user B made. Sounds complicated???

**Comment by alerque** [comment]
Complicated? Not really. If anything it's simplistic in a way that might couse trouble in some edge coses. This might be a case where actually using the underlying VCS to do your dirty work instead of trying to spoon feed it would bring more to the tabel. Merging changes from multiple sources isn't really a wheel you want to be re-inventing.

Hower the architecture to make that possible will take some time to rethink and this is an improvement over what there was before, so...

**Comment by teusbenschop** [comment]
The thing is that if a team consists of five translators, the server would need to maintain five separate git repositories, to enable git to handle all the merges. And that takes, or can take, more space than I would be willing to assign to the team on the Bibledit.org site. 
But more important is that Bibledit merges to the character level. And git only goes to the line level. Which means that git cannot handle the merges that Bibledit can. Hence we need to feed git by spoon this time ☺️

**Comment by alerque** [comment]
> The thing is that if a team consists of five translators, the server would need to maintain five separate git repositories, to enable git to handle all the merges. And that takes, or can take, more space than I would be willing to assign to the team on the Bibledit.org site.

Actually, no it wouldn't. This is inaccurate on several levels¹.

First, even in the event of "separate repositories", you can actually use the same object store between them using either A) a GIT environment variable to set the common store or B) using git's own hard-link mechanism on clone.

However a separate clone isn't necessary even to get separate working directories. Another level of improvement would be git's subtree mechanism that allows you to checkout separate branches or folders into the current working copy and still operate on them against their other branch positions. That would be easy to adapt to BE's current way of dealing with the filesystem and them calling git porcelain commands from a shell. It would work and would bring the overhead down to from having a repository per user to having a working copy per user which is _much_ smaller.

However this is fundamentally brittle and not what BE should be doing long term. At the very least it should be hooking into plumbing commands instead. These commands would also make it possible to write to and merge from different branches per user directly without having the overhead of an extra copy in the file system. This would bring the server resources down to zero overhead to track user changes in git branches. Git branches are, after all, lightweight and tracking changes per user would be no different than tracking changes per commit.

But that's still not quite the right approach. Since this is a C++ based app and all the calls to git are done from the "server" component (even if that is local to the app) and the user never interacts with the underlying file structure, BE could really be using libgit2 to bring the VCS functionality right into the application logic. There should be no need for a working copy in the filesystem at all.

> But more important is that Bibledit merges to the character level. And git only goes to the line level.

That's only really a limitation of the out of the box porcelain commands. Even many of the porcelain commands can work at word or character levels (for example try `git diff --word-diff=color --word-diff-regex=.` sometime on some changeset). There are built in merge strategies that are better than others at handling changes inside the same lines, and most notably you can teach it new merge strategies or call out to an external merge tool. In other words instead of spoon feeding data that's been pre-processed (and then passing it more data that looks like a clobber even if it's been resolved) we could actually teach it to fish—make the data flow through the VCS mechanism in a way where the process is transparent but use a merge strategy that knows, for example, how not to break USFM tags.

¹ <sub>I'm not even mentioning the file-system level where a COW filesystem such as BTRFS or ZFS would automatically eliminate the on-disk overhead involved in having duplicate file structures in various places in the filesystem.</sub>

**Comment by teusbenschop** [comment]
Thanks for mentioning the other ways whereby git could merge the various users and at the same time saving space on disk even in the case of many users.

Even so when merge depended on git, as it did in the past, there were times that git indicated a merge conflict as it didn't know the exact merge required in a situation of a conflicting set of merges.
Bibledit solved that by never getting in a state of conflict, but always choosing one merge strategy or another. It also used to email the two conflicting change sets to the user who brought in the change, so the user could manually review the change and re-submit it or leave it.

After some time this email was removed again.

So I believe that now the merge strategy built into Bibledit is very robust and user friendly (the email would have to be enabled again for transparency on what's happening - it now silently gives preference to one change set to avoid a merge conflict).
But I have to correct one thing, and that is, that currently, with conflicting change sets, I've seen Bibledit merge to the character leven, and actually putting in the conflicting characters side by side. The result of this is that the changes appear in the change modifications next day for anyone to review them.

Why I am saying this? The reason is that I think that the merge capabilities of Bibledit are now so refined that they excel in quality as compared to what git can do.
And the basic thing always to remember is that git is not needed at all. Bibledit does very well without git. Git is just an extra, but not something to rely on: I'd rather get rid of it, really.

As for llibgit2, Bibledit has been using it for a while, but I didn't get it working for the full 100% and there were big API changes at that time, and libgit2 had not yet reached the state of having a stable API (as the developers themselves said), so I thought it was not yet ready for prime time.

So yes, git is OK to have as an extra, and perhaps for statistics, but never to rely on it, or depend on it.

Most bibledit installations have git disabled - there's only a few I know of that use it.

**Comment by teusbenschop** [comment]
But honour is to be given where it is due: The connection to a git repository has one big advantage, and that is that is has a history of changes made, and that history is permanent. This helps restoring something that was accidentally deleted from the Bible text, or that was overwritten by mistake. And that is where git is very good at. :)
