### ISSUE TITLE
Bibledit behind proxy server not reachable by client apps

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#95]
I can't figure out how to connect apps (such as the OSX app) to a Bibledit Cloud instance that is running behind a proxy server (in my case to SSL secure the link between the user and the server).

The port Bibledit is listening on is not accessible except through a VPN. Entering the domain and port of the HTTPS proxy that is world accessible results in the following error:

> Could not make the connection with Bibledit Cloud: Response code: 400 Bad Request 

This is related to #93, but likely not quite the same issue.

**Comment by teusbenschop** [comment]
Possibly it is because the clients don't know anything of SSL. The ssl library is not used. If I remember well, the reason was that the cURL library did not compile across all platforms. Being able to run on all supported platform is necessary for a library to be used. I'd say that it the clients were to connect straight to Bibledit Cloud bypassing the SSL, it would work.

**Comment by alerque** [comment]
Connecting straight to a non-SSL port on the internet is not a workable option for my team—nor should it even be an option for anybody. User data shouldn't be traveling over unsecured channels. The country I live in requires ISP's to monitor all traffic: sometimes they filter it, sometimes they snoop on it, sometimes they munge it. I know for a fact from honey pot testing that usernames, emails and passwords passed over HTTP connections from our church are routinely scraped and later probed.

Currently my only solution is to allow direct access to the BE port to clients connected to the server via VPN. That's kind of a silly and cumbersome work around for an otherwise solved problem. Communication between any app and its central server should be always SSL secured. I'm sure there are ways to do this on every platform. In fact I have to imagine there is a C++ library to handle this uniformly across all platforms, we just have to figure out  what it is.

**Comment by teusbenschop** [comment]
I agree with you on all of the points raised, and have made a note that this needs to be implemented so that it works out of the box without setting up a complicated VPN.
Perhaps the library needed would be https://www.wolfssl.com/wolfSSL/Home.html.

**Comment by teusbenschop** [comment]
Since commit https://github.com/teusbenschop/bibledit/commit/32a1b6245897cbf606deb55fae86e10ece799bbe the clients now can use https to communicate with the Cloud. I have not tested whether this also works to connect to a secure proxy, but would expect that with the option in the cloud to set the user-facing URL, that the client can now securely talk to the proxy server.

**Comment by alerque** [comment]
Is the Mac app store release up to that point yet? I'll test it with my current proxy arrangement when I get a chance. In fact I'll probably keep running that arrangement indefinitely (so it can be on port 443 and to mix and match deployment issues across servers/versions/users), bit it will be really nice to connect directly from clients without having to go through a VPN.

**Comment by teusbenschop** [comment]
The Mac app store release is not yet up to that point, and it will take a while, because I've just updated the Mac store release. The next Mac app release will include the https capability for clients. If all's well, after this update, you'll receive a notification on your desktop that an upgrade is available.
